name: Trigger Webhook on Push to Master

on:
  push:
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send webhook
      run: |
        curl -X POST -H "Content-Type: application/json" \
        --data '{"ref": "${{ github.ref }}", "after": "${{ github.sha }}"}' \
        http://162.19.78.232:5000/webhook-handler/explorer

